# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 17:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('celular', models.IntegerField(blank=True)),
                ('latitud', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
                ('precio_total', models.CharField(max_length=30)),
                ('distancia', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_pedido', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('encargado', models.CharField(blank=True, max_length=30, null=True)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=200)),
                ('fecha_programado', models.DateField(null=True)),
                ('hora_programado', models.TimeField(null=True)),
                ('fecha_aceptado', models.DateField(blank=True, null=True)),
                ('hora_aceptado', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_contador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=30)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('hora_atencion_inicio', models.TimeField(max_length=20)),
                ('hora_atencion_fin', models.TimeField(max_length=20)),
                ('fechas_de_atencion', models.CharField(max_length=25)),
                ('rango_delivery', models.CharField(max_length=10)),
                ('costo_delivery', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(blank=True)),
                ('puesto', models.CharField(choices=[('Sp', 'Supervisor'), ('En', 'Encargado')], max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='app.modelo_empresa')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.modelo_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='modelo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app.modelo_empresa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='modelo_encargado',
            unique_together=set([('nombre', 'empresa')]),
        ),
    ]
