# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=30)),
                ('apellido', models.CharField(blank=True, default='', max_length=30)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('encargado', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='modelo_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.modelo_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='modelo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
    ]
