# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelnotidications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pasada', models.IntegerField(default=0)),
            ],
        ),
    ]
