# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_cliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
