# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 23:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modelo_cliente')),
            ],
        ),
    ]
