# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180427_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_cliente',
            name='empresa_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
