# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 00:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_estado',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='modelo_cliente',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='modelo_estado',
        ),
    ]
