# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelo_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_cliente',
            name='distancia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
