# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_modelo_cliente_empresa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo_cliente',
            name='empresa_id',
        ),
    ]
